"""The canonical source registry seed (blueprint §3.1, 17 rows).

Each row is DATA. Adding source #18 is appending a dict here (or an INSERT via
the admin API), never a code change to a crawler. ``crawler_key`` resolves to a
crawler class at run time; ``config`` holds crawler-specific settings.
"""

from __future__ import annotations

from typing import Any

from warehouse.enums import SourceCategory

SEED_SOURCES: list[dict[str, Any]] = [
    {
        "source_name": "YEIDA Master Plan 2041 + GIS Portal",
        "category": SourceCategory.planning,
        "access_method": "pdf_gis_scrape",
        "refresh_cadence": "monthly",
        "legal_basis": "public govt document",
        "base_url": "https://www.yeida.co.in/",
        "crawler_key": "yeida",
        "config": {"document_list_urls": ["https://www.yeida.co.in/master-plan"]},
    },
    {
        "source_name": "Noida & Greater Noida Authority",
        "category": SourceCategory.planning,
        "access_method": "site_scrape",
        "refresh_cadence": "weekly",
        "legal_basis": "public",
        "base_url": "https://www.noidaauthorityonline.in/",
        "crawler_key": "noida_authority",
        "config": {"start_urls": ["https://www.noidaauthorityonline.in/"]},
    },
    {
        "source_name": "DMRC / NMRC",
        "category": SourceCategory.metro,
        "access_method": "site_tender_scrape",
        "refresh_cadence": "weekly",
        "legal_basis": "public",
        "base_url": "https://www.delhimetrorail.com/",
        "crawler_key": "dmrc",
        "config": {
            "start_urls": [
                "https://www.delhimetrorail.com/",
                "https://www.nmrcnoida.com/",
            ],
            "tender_urls": ["https://www.delhimetrorail.com/tenders"],
        },
    },
    {
        "source_name": "NHAI",
        "category": SourceCategory.highways,
        "access_method": "site_api",
        "refresh_cadence": "weekly",
        "legal_basis": "public",
        "base_url": "https://nhai.gov.in/",
        "crawler_key": "nhai",
        "config": {"start_urls": ["https://nhai.gov.in/"]},
    },
    {
        "source_name": "NCRTC (RRTS)",
        "category": SourceCategory.rrts,
        "access_method": "site_scrape",
        "refresh_cadence": "weekly",
        "legal_basis": "public",
        "base_url": "https://ncrtc.in/",
        "crawler_key": "ncrtc",
        "config": {"start_urls": ["https://ncrtc.in/"]},
    },
    {
        "source_name": "Noida International Airport (Jewar)",
        "category": SourceCategory.airport,
        "access_method": "press_site",
        "refresh_cadence": "weekly",
        "legal_basis": "public",
        "base_url": "https://www.nia.co.in/",
        "crawler_key": "jewar_airport",
        "config": {"start_urls": ["https://www.nia.co.in/"]},
    },
    {
        "source_name": "CPPP / GeM",
        "category": SourceCategory.tenders,
        "access_method": "tender_api",
        "refresh_cadence": "daily",
        "legal_basis": "public procurement (open)",
        "base_url": "https://eprocure.gov.in/",
        "crawler_key": "tender",
        "config": {"api_url": "https://eprocure.gov.in/cppp/tendersfullview", "params": {}},
    },
    {
        "source_name": "data.gov.in",
        "category": SourceCategory.open_data,
        "access_method": "api",
        "refresh_cadence": "weekly",
        "legal_basis": "Open Government Data license",
        "base_url": "https://api.data.gov.in/",
        "crawler_key": "datagov",
        "config": {"api_url": "https://api.data.gov.in/resource", "resource_ids": []},
    },
    {
        "source_name": "UP-RERA",
        "category": SourceCategory.rera,
        "access_method": "site_scrape",
        "refresh_cadence": "weekly",
        "legal_basis": "public regulator record",
        "base_url": "https://www.up-rera.in/",
        "crawler_key": "rera",
        "config": {"search_url": "https://www.up-rera.in/projects"},
    },
    {
        "source_name": "CPCB (CAAQMS)",
        "category": SourceCategory.air_quality,
        "access_method": "api",
        "refresh_cadence": "daily",
        "legal_basis": "public",
        "base_url": "https://airquality.cpcb.gov.in/",
        "crawler_key": "cpcb",
        "config": {"api_url": "https://airquality.cpcb.gov.in/caaqms/", "stations": []},
    },
    {
        "source_name": "CWC + IMD",
        "category": SourceCategory.flood,
        "access_method": "api",
        "refresh_cadence": "daily",
        "legal_basis": "public",
        "base_url": "https://ffs.india-water.gov.in/",
        "crawler_key": "cwc_imd",
        "config": {"api_url": "https://ffs.india-water.gov.in/"},
    },
    {
        "source_name": "CGWB",
        "category": SourceCategory.groundwater,
        "access_method": "dataset_download",
        "refresh_cadence": "quarterly",
        "legal_basis": "public",
        "base_url": "https://cgwb.gov.in/",
        "crawler_key": "cgwb",
        "config": {"dataset_urls": []},
    },
    {
        "source_name": "Survey of India / SRTM (NASA) / Bhuvan (ISRO)",
        "category": SourceCategory.elevation,
        "access_method": "dataset_download",
        "refresh_cadence": "yearly",
        "legal_basis": "public",
        "base_url": "https://bhuvan.nrsc.gov.in/",
        "crawler_key": "dem",
        "config": {"dataset_urls": []},
    },
    {
        "source_name": "Sentinel-2 (ESA Copernicus)",
        "category": SourceCategory.satellite,
        "access_method": "api",
        "refresh_cadence": "5-10 days",
        "legal_basis": "open license",
        "base_url": "https://dataspace.copernicus.eu/",
        "crawler_key": "satellite",
        "config": {"collection": "SENTINEL-2", "fallback": "bhuvan"},
    },
    {
        "source_name": "News aggregators (local + national)",
        "category": SourceCategory.news,
        "access_method": "rss_nlp",
        "refresh_cadence": "daily",
        "legal_basis": "fair-use aggregation w/ attribution",
        "base_url": "",
        "crawler_key": "news",
        "config": {"feeds": []},
    },
    {
        "source_name": "X (Twitter) API",
        "category": SourceCategory.social,
        "access_method": "paid_api",
        "refresh_cadence": "daily",
        "legal_basis": "paid API terms",
        "base_url": "https://api.twitter.com/",
        "crawler_key": "x_social",
        "config": {"enabled": False, "queries": []},  # OFF by default (cost, §3.6/§13)
    },
    {
        "source_name": "Builder investor filings / press",
        "category": SourceCategory.builder,
        "access_method": "scrape",
        "refresh_cadence": "monthly",
        "legal_basis": "public",
        "base_url": "",
        "crawler_key": "builder_press",
        "config": {"start_urls": []},
    },
]
