"""Standard prediction envelope helpers (blueprint §5, P3.2).

Every model in this package returns the shared ``PredictionEnvelope`` from
``warehouse.schemas`` so the rule-weighted score (Phase 2) and the ML models
(Phase 3) are interchangeable to consumers. Advisory numbers are always expressed
as a *band* (low/high) with a disclaimer — never a bare scalar (§5, §13).
"""

from __future__ import annotations

from warehouse.schemas import ContributingFactor, PredictionEnvelope

# Horizon framing (§5 "accuracy framing"): 1-5yr forecasts are moderate-confidence
# ranges; 10yr+ is directional only, never a specific number.
HORIZON_SHORT = "1-5yr"
HORIZON_MEDIUM = "5-10yr"
HORIZON_DIRECTIONAL = "10yr+"

DEFAULT_DISCLAIMER = (
    "Estimate, not investment advice. Shown as a range with a confidence level, "
    "generated by a statistical model from historical data."
)

# Confidence must never be claimed as certainty for advisory numbers.
MAX_ADVISORY_CONFIDENCE = 0.9


def horizon_for_years(years: int) -> str:
    """Map a forecast horizon in years to its framing label (§5)."""
    if years <= 5:
        return HORIZON_SHORT
    if years <= 10:
        return HORIZON_MEDIUM
    return HORIZON_DIRECTIONAL


def banded_envelope(
    *,
    point: float,
    low: float,
    high: float,
    confidence: float,
    factors: list[ContributingFactor],
    model_version: str,
    unit: str,
    horizon: str,
    disclaimer: str = DEFAULT_DISCLAIMER,
    confidence_ceiling: float = MAX_ADVISORY_CONFIDENCE,
) -> PredictionEnvelope:
    """Build a banded advisory envelope, enforcing low<=point<=high and a
    confidence ceiling so no model can claim false certainty."""
    lo, hi = sorted((float(low), float(high)))
    pt = min(max(float(point), lo), hi)
    conf = max(0.0, min(float(confidence), confidence_ceiling))
    return PredictionEnvelope(
        prediction=round(pt, 4),
        prediction_low=round(lo, 4),
        prediction_high=round(hi, 4),
        confidence=round(conf, 3),
        contributing_factors=factors,
        model_version=model_version,
        unit=unit,
        horizon=horizon,
        disclaimer=disclaimer,
        data_layer="prediction",
    )


def insufficient_data_envelope(*, model_version: str, unit: str, reason: str) -> PredictionEnvelope:
    """Returned when accumulated data is below the model's sufficiency threshold
    (§5): an explicit low-confidence signal, NOT a fabricated number."""
    return PredictionEnvelope(
        prediction=0.0,
        prediction_low=None,
        prediction_high=None,
        confidence=0.0,
        contributing_factors=[ContributingFactor(factor=reason, weight=0.0)],
        model_version=model_version,
        unit=unit,
        horizon=None,
        disclaimer=(
            "Insufficient historical data to produce a trustworthy forecast. "
            "No estimate is shown rather than a misleading one."
        ),
        data_layer="prediction",
    )


def unavailable_envelope(*, model_version: str, unit: str) -> PredictionEnvelope:
    """Returned by the serving layer when a model artifact cannot be loaded — an
    explicit low-confidence envelope, never an error the UI might mishandle (P3.8)."""
    return PredictionEnvelope(
        prediction=0.0,
        prediction_low=None,
        prediction_high=None,
        confidence=0.0,
        contributing_factors=[ContributingFactor(factor="model unavailable", weight=0.0)],
        model_version=model_version,
        unit=unit,
        horizon=None,
        disclaimer="This forecast is temporarily unavailable.",
        data_layer="prediction",
    )
